name: angular2_benchmarks
version: 2.0.0-alpha.21
authors:
- 0 <Alex Eagle <alexeagle@google.com>>
- 1 <Chirayu Krishnappa <chirayu@google.com>>
- 2 <Jeff Cross <crossj@google.com>>
- 3 <Misko Hevery <misko@google.com>>
- 4 <Rado Kirov <radokirov@google.com>>
- 5 <Tobias Bosch <tbosch@google.com>>
- 6 <Victor Savkin <vsavkin@google.com>>
- 7 <Yegor Jbanov <yjbanov@google.com>>
description: Angular2 benchmarks
homepage: https://github.com/angular/angular
environment:
  sdk: '>=1.9.0-dev.8.0'
dependencies:
  angular2: '^2.0.0-alpha.21'
  browser: '>=0.10.0 <0.11.0'
dependency_overrides:
  angular2:
    path: ../angular2
transformers:
- angular2:
    entry_points:
        - web/src/compiler/compiler_benchmark.dart
        - web/src/costs/index.dart
        - web/src/di/di_benchmark.dart
        - web/src/element_injector/element_injector_benchmark.dart
        - web/src/largetable/largetable_benchmark.dart
        - web/src/naive_infinite_scroll/index.dart
        - web/src/tree/tree_benchmark.dart
- $dart2js:
    minify: false
    commandLineOptions:
    - --dump-info
    - --trust-type-annotations
    - --trust-primitives
    - --show-package-warnings
